# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 03:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=200)),
                ('departamento', models.CharField(max_length=200)),
                ('perfil', models.CharField(choices=[('administrador', 'administrador'), ('operador', 'operador'), ('supervisor', 'supervisor'), ('jefe', 'jefe')], max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('asunto', models.CharField(max_length=500)),
                ('contenido', models.CharField(max_length=500)),
                ('prioridad', models.CharField(choices=[('urgente', 'urgente'), ('estandar', 'estandar'), ('baja', 'baja')], max_length=5)),
                ('cerrador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cerrado_por', to=settings.AUTH_USER_MODEL)),
                ('creador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creado_por', to=settings.AUTH_USER_MODEL)),
                ('encargado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encargado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket'),
        ),
    ]
