# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20170605_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cerrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cerrador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encargado', to=settings.AUTH_USER_MODEL),
        ),
    ]
