# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_filedata_textdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_atacante', models.CharField(max_length=100)),
                ('email_suplantado', models.CharField(max_length=100)),
                ('asunto_correo', models.CharField(max_length=500)),
                ('nro_afectados', models.IntegerField(default=0)),
                ('catalogamiento', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('subtipo', models.CharField(max_length=200)),
                ('clase', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleContenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('link_enmascarado', models.CharField(max_length=100)),
                ('dominio', models.CharField(max_length=300)),
                ('adjunto_name', models.CharField(max_length=100)),
                ('correo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticket.Correo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCorreo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('uurr', models.CharField(max_length=50)),
                ('comprometido', models.BooleanField(default=False)),
                ('comentario', models.CharField(default='', max_length=200)),
                ('correo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticket.Correo')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocalizacion', models.CharField(max_length=10)),
                ('ip_origen', models.CharField(max_length=15)),
                ('ip_destino', models.CharField(max_length=15)),
                ('servicio_afectado', models.CharField(max_length=250)),
                ('alerta_id', models.CharField(max_length=25)),
                ('alerta_name', models.CharField(max_length=25)),
                ('hashsha1', models.CharField(max_length=150)),
                ('hashsha2', models.CharField(max_length=150)),
                ('hashshamd5', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=50)),
                ('subtipo', models.CharField(max_length=200)),
                ('clase', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporte', models.CharField(max_length=500)),
                ('designado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('equipo', models.CharField(max_length=250)),
                ('sector', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='VinculoHijo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VinculoPadre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='resuelto',
        ),
        migrations.AddField(
            model_name='ticket',
            name='cybersystem',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='direccionamiento',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_apertura',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_cierre',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='impacto',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tiempo_aplazado',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vinculopadre',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket'),
        ),
        migrations.AddField(
            model_name='vinculopadre',
            name='ticket_padre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacion_padre', to='ticket.Ticket'),
        ),
        migrations.AddField(
            model_name='vinculohijo',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket'),
        ),
        migrations.AddField(
            model_name='vinculohijo',
            name='ticket_hijo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacion_hijo', to='ticket.Ticket'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket'),
        ),
        migrations.AddField(
            model_name='evento',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket'),
        ),
        migrations.AddField(
            model_name='correo',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket'),
        ),
    ]
