# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20170606_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha_apertura',
            field=models.DateField(auto_now_add=True),
        ),
    ]
