# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_auto_20170607_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='visada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textdata',
            name='visada',
            field=models.BooleanField(default=False),
        ),
    ]
