# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20170607_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='asunto',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='contenido',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
