# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_auto_20170607_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='empleado',
            name='perfil',
            field=models.CharField(choices=[('operador', 'Operador'), ('supervisor', 'Supervisor'), ('jefe', 'Jefe')], max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(choices=[('Urgente', 'Urgente'), ('Estandar', 'Estandar'), ('Baja', 'Baja')], max_length=15),
        ),
        migrations.AddField(
            model_name='vinculo',
            name='ticket_hijo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padre', to='ticket.Ticket'),
        ),
        migrations.AddField(
            model_name='vinculo',
            name='ticket_padre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijo', to='ticket.Ticket'),
        ),
    ]
