# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_auto_20170615_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='aplazado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='asunto',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='contenido',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
