# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 01:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_ticket_tiempo_restante_aplazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha_aplazo',
            field=models.DateField(default=datetime.date(2017, 6, 16), null=True),
        ),
    ]
