# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-26 01:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_auto_20170825_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_aplazo',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 26, 1, 48, 4, 201390, tzinfo=utc), null=True),
        ),
    ]
