# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-26 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_auto_20170825_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha_aplazo',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
