# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0021_auto_20170826_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('TAsignado', 'Ticket asignado'), ('TCerrado', 'Ticket cerrado'), ('TAplazado', 'Ticket aplazado'), ('TCreado', 'Ticket creado'), ('TEliminado', 'Ticket eliminado'), ('TEditado', 'Ticket editado'), ('DCreada', 'Data nueva'), ('DAprobada', 'Data aprobada'), ('DRechazada', 'Data Rechazada'), ('TAbierto', 'Ticket abierto'), ('TRestaurado', 'Ticket restaurado'), ('TVinculado', 'Ticket Vinculado')], max_length=200),
        ),
    ]
